[build]
  command = "npm run build"
  publish = ".next/standalone"

[context.production]
  command = "npm run build"
  environment = { NEXT_PUBLIC_ENV = "production", NEXT_PUBLIC_SITE_URL = "https://app.voluntodo.com" }

[context.staging]
  command = "npm run build"
  environment = { NEXT_PUBLIC_ENV = "staging", NEXT_PUBLIC_SITE_URL = "https://staging.voluntodo.app" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NEXT_PUBLIC_ENV = "preview" }
